// Code generated by optionalize
// on: 2017-10-19 10:05:19.479373494 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type BoolSlice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value []bool)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() ([]bool, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def []bool) []bool

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() []bool) []bool

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() []bool

	// And returns None if the optional is None, otherwise returns optb.
	And(optb BoolSlice) BoolSlice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb BoolSlice) BoolSlice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() BoolSlice) BoolSlice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value []bool)) someBoolSliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someBoolSliceHandler interface {
	None(fn func())
}

type _BoolSlice struct {
	hasValue    bool
	unsafeValue []bool
}

func NewBoolSlice() BoolSlice {
	opt := &_BoolSlice{}
	opt.Take()
	return opt
}

func BoolSliceFrom(value []bool, hasValue bool) BoolSlice {
	opt := &_BoolSlice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_BoolSlice) Take() {
	var value []bool
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_BoolSlice) From(value []bool) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_BoolSlice) Unwrap() ([]bool, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_BoolSlice) UnwrapOr(def []bool) []bool {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_BoolSlice) UnwrapOrElse(fn func() []bool) []bool {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_BoolSlice) UnwrapOrPanic() []bool {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap BoolSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_BoolSlice) And(optb BoolSlice) BoolSlice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_BoolSlice) Or(optb BoolSlice) BoolSlice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_BoolSlice) OrElse(fn func() BoolSlice) BoolSlice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_BoolSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_BoolSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_BoolSlice) Some(fn func(value []bool)) someBoolSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someBoolSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_BoolSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someBoolSliceHandler struct {
	opt *_BoolSlice
}

func (some _someBoolSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_BoolSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_BoolSlice) getUnsafeValue() []bool {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_BoolSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json.Marshaler interface.
func (opt _BoolSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (opt *_BoolSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return err
	}
	opt.hasValue = true

	return nil
}
