// Code generated by optionalize
// on: 2017-10-19 12:55:54.176383754 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/Gurpartap/safer-go/optional/internal/convert"
	"github.com/pkg/errors"
)

type Bytes struct {
	hasValue    bool
	unsafeValue []byte
}

func NewBytes() Bytes {
	opt := &Bytes{}
	opt.Take()
	return *opt
}

func BytesFrom(value []byte, hasValue bool) Bytes {
	opt := &Bytes{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *Bytes) Take() {
	var value []byte
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *Bytes) From(value []byte) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *Bytes) Unwrap() ([]byte, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *Bytes) UnwrapOr(def []byte) []byte {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *Bytes) UnwrapOrElse(fn func() []byte) []byte {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *Bytes) UnwrapOrPanic() []byte {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Bytes")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *Bytes) And(optb Bytes) Bytes {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *Bytes) Or(optb Bytes) Bytes {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *Bytes) OrElse(fn func() Bytes) Bytes {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *Bytes) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *Bytes) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *Bytes) Some(fn func(value []byte)) someBytesHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someBytesHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *Bytes) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someBytesHandler struct {
	opt *Bytes
}

func (some someBytesHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *Bytes) getHasValue() bool {
	return opt.hasValue
}

func (opt *Bytes) getUnsafeValue() []byte {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *Bytes) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt Bytes) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *Bytes) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}

// Scan implements the sql Scanner interface.
func (opt *Bytes) Scan(value interface{}) error {
	if value == nil {
		opt.Take()
		return nil
	}

	var unsafeValue []byte
	err := convert.ConvertAssign(&unsafeValue, value)
	if err != nil {
		return err
	}
	opt.From(unsafeValue)

	return nil
}

// Value implements the driver Valuer interface.
func (opt Bytes) Value() (driver.Value, error) {
	if !opt.getHasValue() {
		return nil, nil
	}
	return opt.getUnsafeValue(), nil
}
