// Code generated by optionalize
// on: 2017-10-19 12:55:59.078094913 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/Gurpartap/safer-go/optional/internal/convert"
	"github.com/pkg/errors"
)

type Complex128Slice struct {
	hasValue    bool
	unsafeValue []complex128
}

func NewComplex128Slice() Complex128Slice {
	opt := &Complex128Slice{}
	opt.Take()
	return *opt
}

func Complex128SliceFrom(value []complex128, hasValue bool) Complex128Slice {
	opt := &Complex128Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *Complex128Slice) Take() {
	var value []complex128
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *Complex128Slice) From(value []complex128) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *Complex128Slice) Unwrap() ([]complex128, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *Complex128Slice) UnwrapOr(def []complex128) []complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *Complex128Slice) UnwrapOrElse(fn func() []complex128) []complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *Complex128Slice) UnwrapOrPanic() []complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Complex128Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *Complex128Slice) And(optb Complex128Slice) Complex128Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *Complex128Slice) Or(optb Complex128Slice) Complex128Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *Complex128Slice) OrElse(fn func() Complex128Slice) Complex128Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *Complex128Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *Complex128Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *Complex128Slice) Some(fn func(value []complex128)) someComplex128SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someComplex128SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *Complex128Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someComplex128SliceHandler struct {
	opt *Complex128Slice
}

func (some someComplex128SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *Complex128Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *Complex128Slice) getUnsafeValue() []complex128 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *Complex128Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt Complex128Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *Complex128Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}

// Scan implements the sql Scanner interface.
func (opt *Complex128Slice) Scan(value interface{}) error {
	if value == nil {
		opt.Take()
		return nil
	}

	var unsafeValue []complex128
	err := convert.ConvertAssign(&unsafeValue, value)
	if err != nil {
		return err
	}
	opt.From(unsafeValue)

	return nil
}

// Value implements the driver Valuer interface.
func (opt Complex128Slice) Value() (driver.Value, error) {
	if !opt.getHasValue() {
		return nil, nil
	}
	return opt.getUnsafeValue(), nil
}
