// Code generated by optionalize
// on: 2017-10-19 12:53:29.52797594 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type ErrorSlice struct {
	hasValue    bool
	unsafeValue []error
}

func NewErrorSlice() ErrorSlice {
	opt := &ErrorSlice{}
	opt.Take()
	return *opt
}

func ErrorSliceFrom(value []error, hasValue bool) ErrorSlice {
	opt := &ErrorSlice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *ErrorSlice) Take() {
	var value []error
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *ErrorSlice) From(value []error) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *ErrorSlice) Unwrap() ([]error, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *ErrorSlice) UnwrapOr(def []error) []error {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *ErrorSlice) UnwrapOrElse(fn func() []error) []error {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *ErrorSlice) UnwrapOrPanic() []error {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap ErrorSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *ErrorSlice) And(optb ErrorSlice) ErrorSlice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *ErrorSlice) Or(optb ErrorSlice) ErrorSlice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *ErrorSlice) OrElse(fn func() ErrorSlice) ErrorSlice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *ErrorSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *ErrorSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *ErrorSlice) Some(fn func(value []error)) someErrorSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someErrorSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *ErrorSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someErrorSliceHandler struct {
	opt *ErrorSlice
}

func (some someErrorSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *ErrorSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *ErrorSlice) getUnsafeValue() []error {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *ErrorSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt ErrorSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *ErrorSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
