// Code generated by optionalize
// on: 2017-10-19 10:05:16.24441489 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type Float64 interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value float64)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (float64, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def float64) float64

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() float64) float64

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() float64

	// And returns None if the optional is None, otherwise returns optb.
	And(optb Float64) Float64

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb Float64) Float64

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() Float64) Float64

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value float64)) someFloat64Handler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someFloat64Handler interface {
	None(fn func())
}

type _Float64 struct {
	hasValue    bool
	unsafeValue float64
}

func NewFloat64() Float64 {
	opt := &_Float64{}
	opt.Take()
	return opt
}

func Float64From(value float64, hasValue bool) Float64 {
	opt := &_Float64{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_Float64) Take() {
	var value float64
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_Float64) From(value float64) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_Float64) Unwrap() (float64, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_Float64) UnwrapOr(def float64) float64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_Float64) UnwrapOrElse(fn func() float64) float64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_Float64) UnwrapOrPanic() float64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Float64")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_Float64) And(optb Float64) Float64 {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_Float64) Or(optb Float64) Float64 {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_Float64) OrElse(fn func() Float64) Float64 {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_Float64) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_Float64) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_Float64) Some(fn func(value float64)) someFloat64Handler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someFloat64Handler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_Float64) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someFloat64Handler struct {
	opt *_Float64
}

func (some _someFloat64Handler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_Float64) getHasValue() bool {
	return opt.hasValue
}

func (opt *_Float64) getUnsafeValue() float64 {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_Float64) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json.Marshaler interface.
func (opt _Float64) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (opt *_Float64) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return err
	}
	opt.hasValue = true

	return nil
}
