// Code generated by optionalize
// on: 2017-10-19 12:53:25.555372081 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type Int16Slice struct {
	hasValue    bool
	unsafeValue []int16
}

func NewInt16Slice() Int16Slice {
	opt := &Int16Slice{}
	opt.Take()
	return *opt
}

func Int16SliceFrom(value []int16, hasValue bool) Int16Slice {
	opt := &Int16Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *Int16Slice) Take() {
	var value []int16
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *Int16Slice) From(value []int16) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *Int16Slice) Unwrap() ([]int16, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *Int16Slice) UnwrapOr(def []int16) []int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *Int16Slice) UnwrapOrElse(fn func() []int16) []int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *Int16Slice) UnwrapOrPanic() []int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Int16Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *Int16Slice) And(optb Int16Slice) Int16Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *Int16Slice) Or(optb Int16Slice) Int16Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *Int16Slice) OrElse(fn func() Int16Slice) Int16Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *Int16Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *Int16Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *Int16Slice) Some(fn func(value []int16)) someInt16SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someInt16SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *Int16Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someInt16SliceHandler struct {
	opt *Int16Slice
}

func (some someInt16SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *Int16Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *Int16Slice) getUnsafeValue() []int16 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *Int16Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt Int16Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *Int16Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
