// Code generated by optionalize
// on: 2017-10-19 08:41:12.395686488 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type Int16Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value []int16)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() ([]int16, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def []int16) []int16

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() []int16) []int16

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() []int16

	// And returns None if the optional is None, otherwise returns optb.
	And(optb Int16Slice) Int16Slice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb Int16Slice) Int16Slice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() Int16Slice) Int16Slice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value []int16)) someInt16SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someInt16SliceHandler interface {
	None(fn func())
}

type _Int16Slice struct {
	hasValue    bool
	unsafeValue []int16
}

// String conforms to fmt.Stringer interface.
func (opt *_Int16Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewInt16Slice() Int16Slice {
	opt := &_Int16Slice{}
	opt.Take()
	return opt
}

func Int16SliceFrom(value []int16, hasValue bool) Int16Slice {
	opt := &_Int16Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_Int16Slice) Take() {
	var value []int16
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_Int16Slice) From(value []int16) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_Int16Slice) Unwrap() ([]int16, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_Int16Slice) UnwrapOr(def []int16) []int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_Int16Slice) UnwrapOrElse(fn func() []int16) []int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_Int16Slice) UnwrapOrPanic() []int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Int16Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_Int16Slice) And(optb Int16Slice) Int16Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_Int16Slice) Or(optb Int16Slice) Int16Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_Int16Slice) OrElse(fn func() Int16Slice) Int16Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_Int16Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_Int16Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_Int16Slice) Some(fn func(value []int16)) someInt16SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someInt16SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_Int16Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someInt16SliceHandler struct {
	opt *_Int16Slice
}

func (some _someInt16SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_Int16Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_Int16Slice) getUnsafeValue() []int16 {
	return opt.unsafeValue
}
