// Code generated by optionalize
// on: 2017-10-19 10:35:50.360192058 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type Int16 interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value int16)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (int16, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def int16) int16

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() int16) int16

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() int16

	// And returns None if the optional is None, otherwise returns optb.
	And(optb Int16) Int16

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb Int16) Int16

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() Int16) Int16

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value int16)) someInt16Handler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someInt16Handler interface {
	None(fn func())
}

type _Int16 struct {
	hasValue    bool
	unsafeValue int16
}

func NewInt16() Int16 {
	opt := &_Int16{}
	opt.Take()
	return opt
}

func Int16From(value int16, hasValue bool) Int16 {
	opt := &_Int16{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_Int16) Take() {
	var value int16
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_Int16) From(value int16) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_Int16) Unwrap() (int16, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_Int16) UnwrapOr(def int16) int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_Int16) UnwrapOrElse(fn func() int16) int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_Int16) UnwrapOrPanic() int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Int16")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_Int16) And(optb Int16) Int16 {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_Int16) Or(optb Int16) Int16 {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_Int16) OrElse(fn func() Int16) Int16 {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_Int16) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_Int16) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_Int16) Some(fn func(value int16)) someInt16Handler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someInt16Handler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_Int16) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someInt16Handler struct {
	opt *_Int16
}

func (some _someInt16Handler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_Int16) getHasValue() bool {
	return opt.hasValue
}

func (opt *_Int16) getUnsafeValue() int16 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *_Int16) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt _Int16) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *_Int16) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
