// Code generated by optionalize
// on: 2017-10-19 12:55:57.525857802 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/Gurpartap/safer-go/optional/internal/convert"
	"github.com/pkg/errors"
)

type Int32Slice struct {
	hasValue    bool
	unsafeValue []int32
}

func NewInt32Slice() Int32Slice {
	opt := &Int32Slice{}
	opt.Take()
	return *opt
}

func Int32SliceFrom(value []int32, hasValue bool) Int32Slice {
	opt := &Int32Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *Int32Slice) Take() {
	var value []int32
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *Int32Slice) From(value []int32) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *Int32Slice) Unwrap() ([]int32, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *Int32Slice) UnwrapOr(def []int32) []int32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *Int32Slice) UnwrapOrElse(fn func() []int32) []int32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *Int32Slice) UnwrapOrPanic() []int32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Int32Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *Int32Slice) And(optb Int32Slice) Int32Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *Int32Slice) Or(optb Int32Slice) Int32Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *Int32Slice) OrElse(fn func() Int32Slice) Int32Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *Int32Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *Int32Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *Int32Slice) Some(fn func(value []int32)) someInt32SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someInt32SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *Int32Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someInt32SliceHandler struct {
	opt *Int32Slice
}

func (some someInt32SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *Int32Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *Int32Slice) getUnsafeValue() []int32 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *Int32Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt Int32Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *Int32Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}

// Scan implements the sql Scanner interface.
func (opt *Int32Slice) Scan(value interface{}) error {
	if value == nil {
		opt.Take()
		return nil
	}

	var unsafeValue []int32
	err := convert.ConvertAssign(&unsafeValue, value)
	if err != nil {
		return err
	}
	opt.From(unsafeValue)

	return nil
}

// Value implements the driver Valuer interface.
func (opt Int32Slice) Value() (driver.Value, error) {
	if !opt.getHasValue() {
		return nil, nil
	}
	return opt.getUnsafeValue(), nil
}
