// Code generated by optionalize
// on: 2017-10-19 08:58:21.839287426 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type Int8Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value []int8)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() ([]int8, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def []int8) []int8

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() []int8) []int8

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() []int8

	// And returns None if the optional is None, otherwise returns optb.
	And(optb Int8Slice) Int8Slice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb Int8Slice) Int8Slice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() Int8Slice) Int8Slice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value []int8)) someInt8SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someInt8SliceHandler interface {
	None(fn func())
}

type _Int8Slice struct {
	hasValue    bool
	unsafeValue []int8
}

func NewInt8Slice() Int8Slice {
	opt := &_Int8Slice{}
	opt.Take()
	return opt
}

func Int8SliceFrom(value []int8, hasValue bool) Int8Slice {
	opt := &_Int8Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_Int8Slice) Take() {
	var value []int8
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_Int8Slice) From(value []int8) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_Int8Slice) Unwrap() ([]int8, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_Int8Slice) UnwrapOr(def []int8) []int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_Int8Slice) UnwrapOrElse(fn func() []int8) []int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_Int8Slice) UnwrapOrPanic() []int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap Int8Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_Int8Slice) And(optb Int8Slice) Int8Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_Int8Slice) Or(optb Int8Slice) Int8Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_Int8Slice) OrElse(fn func() Int8Slice) Int8Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_Int8Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_Int8Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_Int8Slice) Some(fn func(value []int8)) someInt8SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someInt8SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_Int8Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someInt8SliceHandler struct {
	opt *_Int8Slice
}

func (some _someInt8SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_Int8Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_Int8Slice) getUnsafeValue() []int8 {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_Int8Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}
