// Code generated by optionalize
// on: 2017-10-19 08:58:29.477684192 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalInt64Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Int64)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Int64, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Int64) Int64

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Int64) Int64

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Int64

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalInt64Slice) OptionalInt64Slice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb OptionalInt64Slice) OptionalInt64Slice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() OptionalInt64Slice) OptionalInt64Slice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Int64)) someOptionalInt64SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalInt64SliceHandler interface {
	None(fn func())
}

type _OptionalInt64Slice struct {
	hasValue    bool
	unsafeValue Int64
}

func NewOptionalInt64Slice() OptionalInt64Slice {
	opt := &_OptionalInt64Slice{}
	opt.Take()
	return opt
}

func OptionalInt64SliceFrom(value Int64, hasValue bool) OptionalInt64Slice {
	opt := &_OptionalInt64Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_OptionalInt64Slice) Take() {
	var value Int64
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalInt64Slice) From(value Int64) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalInt64Slice) Unwrap() (Int64, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalInt64Slice) UnwrapOr(def Int64) Int64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalInt64Slice) UnwrapOrElse(fn func() Int64) Int64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalInt64Slice) UnwrapOrPanic() Int64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalInt64Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalInt64Slice) And(optb OptionalInt64Slice) OptionalInt64Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_OptionalInt64Slice) Or(optb OptionalInt64Slice) OptionalInt64Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalInt64Slice) OrElse(fn func() OptionalInt64Slice) OptionalInt64Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_OptionalInt64Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_OptionalInt64Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalInt64Slice) Some(fn func(value Int64)) someOptionalInt64SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalInt64SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalInt64Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalInt64SliceHandler struct {
	opt *_OptionalInt64Slice
}

func (some _someOptionalInt64SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalInt64Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalInt64Slice) getUnsafeValue() Int64 {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalInt64Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}
