// Code generated by optionalize
// on: 2017-10-19 12:53:33.732182979 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type OptionalComplex128Slice struct {
	hasValue    bool
	unsafeValue Complex128
}

func NewOptionalComplex128Slice() OptionalComplex128Slice {
	opt := &OptionalComplex128Slice{}
	opt.Take()
	return *opt
}

func OptionalComplex128SliceFrom(value Complex128, hasValue bool) OptionalComplex128Slice {
	opt := &OptionalComplex128Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalComplex128Slice) Take() {
	var value Complex128
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalComplex128Slice) From(value Complex128) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalComplex128Slice) Unwrap() (Complex128, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalComplex128Slice) UnwrapOr(def Complex128) Complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalComplex128Slice) UnwrapOrElse(fn func() Complex128) Complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalComplex128Slice) UnwrapOrPanic() Complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalComplex128Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalComplex128Slice) And(optb OptionalComplex128Slice) OptionalComplex128Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalComplex128Slice) Or(optb OptionalComplex128Slice) OptionalComplex128Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalComplex128Slice) OrElse(fn func() OptionalComplex128Slice) OptionalComplex128Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalComplex128Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalComplex128Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalComplex128Slice) Some(fn func(value Complex128)) someOptionalComplex128SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalComplex128SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalComplex128Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalComplex128SliceHandler struct {
	opt *OptionalComplex128Slice
}

func (some someOptionalComplex128SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalComplex128Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalComplex128Slice) getUnsafeValue() Complex128 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalComplex128Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalComplex128Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalComplex128Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
