// Code generated by optionalize
// on: 2017-10-19 12:53:31.935185295 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type OptionalInt16Slice struct {
	hasValue    bool
	unsafeValue Int16
}

func NewOptionalInt16Slice() OptionalInt16Slice {
	opt := &OptionalInt16Slice{}
	opt.Take()
	return *opt
}

func OptionalInt16SliceFrom(value Int16, hasValue bool) OptionalInt16Slice {
	opt := &OptionalInt16Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalInt16Slice) Take() {
	var value Int16
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalInt16Slice) From(value Int16) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalInt16Slice) Unwrap() (Int16, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalInt16Slice) UnwrapOr(def Int16) Int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalInt16Slice) UnwrapOrElse(fn func() Int16) Int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalInt16Slice) UnwrapOrPanic() Int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalInt16Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalInt16Slice) And(optb OptionalInt16Slice) OptionalInt16Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalInt16Slice) Or(optb OptionalInt16Slice) OptionalInt16Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalInt16Slice) OrElse(fn func() OptionalInt16Slice) OptionalInt16Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalInt16Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalInt16Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalInt16Slice) Some(fn func(value Int16)) someOptionalInt16SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalInt16SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalInt16Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalInt16SliceHandler struct {
	opt *OptionalInt16Slice
}

func (some someOptionalInt16SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalInt16Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalInt16Slice) getUnsafeValue() Int16 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalInt16Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalInt16Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalInt16Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
