// Code generated by optionalize
// on: 2017-09-10 10:30:46.121688464 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalInt16Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Int16)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Int16, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Int16) Int16

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Int16) Int16

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Int16

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalInt16Slice) OptionalInt16Slice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb OptionalInt16Slice) OptionalInt16Slice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() OptionalInt16Slice) OptionalInt16Slice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Int16)) someOptionalInt16SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalInt16SliceHandler interface {
	None(fn func())
}

type _OptionalInt16Slice struct {
	hasValue    bool
	unsafeValue Int16
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalInt16Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewOptionalInt16Slice() OptionalInt16Slice {
	opt := &_OptionalInt16Slice{}
	opt.Take()
	return opt
}

func OptionalInt16SliceFrom(value Int16) OptionalInt16Slice {
	opt := &_OptionalInt16Slice{}
	opt.From(value)
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_OptionalInt16Slice) Take() {
	var value Int16
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalInt16Slice) From(value Int16) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalInt16Slice) Unwrap() (Int16, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalInt16Slice) UnwrapOr(def Int16) Int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalInt16Slice) UnwrapOrElse(fn func() Int16) Int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalInt16Slice) UnwrapOrPanic() Int16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalInt16Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalInt16Slice) And(optb OptionalInt16Slice) OptionalInt16Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_OptionalInt16Slice) Or(optb OptionalInt16Slice) OptionalInt16Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalInt16Slice) OrElse(fn func() OptionalInt16Slice) OptionalInt16Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_OptionalInt16Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_OptionalInt16Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalInt16Slice) Some(fn func(value Int16)) someOptionalInt16SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalInt16SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalInt16Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalInt16SliceHandler struct {
	opt *_OptionalInt16Slice
}

func (some _someOptionalInt16SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalInt16Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalInt16Slice) getUnsafeValue() Int16 {
	return opt.unsafeValue
}
