// Code generated by optionalize
// on: 2017-10-19 08:58:28.486837719 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalInt8Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Int8)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Int8, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Int8) Int8

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Int8) Int8

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Int8

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalInt8Slice) OptionalInt8Slice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb OptionalInt8Slice) OptionalInt8Slice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() OptionalInt8Slice) OptionalInt8Slice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Int8)) someOptionalInt8SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalInt8SliceHandler interface {
	None(fn func())
}

type _OptionalInt8Slice struct {
	hasValue    bool
	unsafeValue Int8
}

func NewOptionalInt8Slice() OptionalInt8Slice {
	opt := &_OptionalInt8Slice{}
	opt.Take()
	return opt
}

func OptionalInt8SliceFrom(value Int8, hasValue bool) OptionalInt8Slice {
	opt := &_OptionalInt8Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_OptionalInt8Slice) Take() {
	var value Int8
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalInt8Slice) From(value Int8) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalInt8Slice) Unwrap() (Int8, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalInt8Slice) UnwrapOr(def Int8) Int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalInt8Slice) UnwrapOrElse(fn func() Int8) Int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalInt8Slice) UnwrapOrPanic() Int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalInt8Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalInt8Slice) And(optb OptionalInt8Slice) OptionalInt8Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_OptionalInt8Slice) Or(optb OptionalInt8Slice) OptionalInt8Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalInt8Slice) OrElse(fn func() OptionalInt8Slice) OptionalInt8Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_OptionalInt8Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_OptionalInt8Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalInt8Slice) Some(fn func(value Int8)) someOptionalInt8SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalInt8SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalInt8Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalInt8SliceHandler struct {
	opt *_OptionalInt8Slice
}

func (some _someOptionalInt8SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalInt8Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalInt8Slice) getUnsafeValue() Int8 {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalInt8Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}
