// Code generated by optionalize
// on: 2017-10-19 08:41:20.233687964 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalComplex64Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Complex64)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Complex64, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Complex64) Complex64

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Complex64) Complex64

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Complex64

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalComplex64Slice) OptionalComplex64Slice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb OptionalComplex64Slice) OptionalComplex64Slice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() OptionalComplex64Slice) OptionalComplex64Slice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Complex64)) someOptionalComplex64SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalComplex64SliceHandler interface {
	None(fn func())
}

type _OptionalComplex64Slice struct {
	hasValue    bool
	unsafeValue Complex64
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalComplex64Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewOptionalComplex64Slice() OptionalComplex64Slice {
	opt := &_OptionalComplex64Slice{}
	opt.Take()
	return opt
}

func OptionalComplex64SliceFrom(value Complex64, hasValue bool) OptionalComplex64Slice {
	opt := &_OptionalComplex64Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_OptionalComplex64Slice) Take() {
	var value Complex64
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalComplex64Slice) From(value Complex64) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalComplex64Slice) Unwrap() (Complex64, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalComplex64Slice) UnwrapOr(def Complex64) Complex64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalComplex64Slice) UnwrapOrElse(fn func() Complex64) Complex64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalComplex64Slice) UnwrapOrPanic() Complex64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalComplex64Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalComplex64Slice) And(optb OptionalComplex64Slice) OptionalComplex64Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_OptionalComplex64Slice) Or(optb OptionalComplex64Slice) OptionalComplex64Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalComplex64Slice) OrElse(fn func() OptionalComplex64Slice) OptionalComplex64Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_OptionalComplex64Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_OptionalComplex64Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalComplex64Slice) Some(fn func(value Complex64)) someOptionalComplex64SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalComplex64SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalComplex64Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalComplex64SliceHandler struct {
	opt *_OptionalComplex64Slice
}

func (some _someOptionalComplex64SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalComplex64Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalComplex64Slice) getUnsafeValue() Complex64 {
	return opt.unsafeValue
}
