// Code generated by optionalize
// on: 2017-10-19 12:53:35.213998094 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type OptionalRuneSlice struct {
	hasValue    bool
	unsafeValue Rune
}

func NewOptionalRuneSlice() OptionalRuneSlice {
	opt := &OptionalRuneSlice{}
	opt.Take()
	return *opt
}

func OptionalRuneSliceFrom(value Rune, hasValue bool) OptionalRuneSlice {
	opt := &OptionalRuneSlice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalRuneSlice) Take() {
	var value Rune
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalRuneSlice) From(value Rune) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalRuneSlice) Unwrap() (Rune, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalRuneSlice) UnwrapOr(def Rune) Rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalRuneSlice) UnwrapOrElse(fn func() Rune) Rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalRuneSlice) UnwrapOrPanic() Rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalRuneSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalRuneSlice) And(optb OptionalRuneSlice) OptionalRuneSlice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalRuneSlice) Or(optb OptionalRuneSlice) OptionalRuneSlice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalRuneSlice) OrElse(fn func() OptionalRuneSlice) OptionalRuneSlice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalRuneSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalRuneSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalRuneSlice) Some(fn func(value Rune)) someOptionalRuneSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalRuneSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalRuneSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalRuneSliceHandler struct {
	opt *OptionalRuneSlice
}

func (some someOptionalRuneSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalRuneSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalRuneSlice) getUnsafeValue() Rune {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalRuneSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalRuneSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalRuneSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
