// Code generated by optionalize
// on: 2017-09-10 10:30:47.963344376 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalComplex128Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Complex128)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Complex128, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Complex128) Complex128

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Complex128) Complex128

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Complex128

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalComplex128Slice) OptionalComplex128Slice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb OptionalComplex128Slice) OptionalComplex128Slice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() OptionalComplex128Slice) OptionalComplex128Slice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Complex128)) someOptionalComplex128SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalComplex128SliceHandler interface {
	None(fn func())
}

type _OptionalComplex128Slice struct {
	hasValue    bool
	unsafeValue Complex128
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalComplex128Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewOptionalComplex128Slice() OptionalComplex128Slice {
	opt := &_OptionalComplex128Slice{}
	opt.Take()
	return opt
}

func OptionalComplex128SliceFrom(value Complex128) OptionalComplex128Slice {
	opt := &_OptionalComplex128Slice{}
	opt.From(value)
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_OptionalComplex128Slice) Take() {
	var value Complex128
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalComplex128Slice) From(value Complex128) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalComplex128Slice) Unwrap() (Complex128, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalComplex128Slice) UnwrapOr(def Complex128) Complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalComplex128Slice) UnwrapOrElse(fn func() Complex128) Complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalComplex128Slice) UnwrapOrPanic() Complex128 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalComplex128Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalComplex128Slice) And(optb OptionalComplex128Slice) OptionalComplex128Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_OptionalComplex128Slice) Or(optb OptionalComplex128Slice) OptionalComplex128Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalComplex128Slice) OrElse(fn func() OptionalComplex128Slice) OptionalComplex128Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_OptionalComplex128Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_OptionalComplex128Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalComplex128Slice) Some(fn func(value Complex128)) someOptionalComplex128SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalComplex128SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalComplex128Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalComplex128SliceHandler struct {
	opt *_OptionalComplex128Slice
}

func (some _someOptionalComplex128SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalComplex128Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalComplex128Slice) getUnsafeValue() Complex128 {
	return opt.unsafeValue
}
