// Code generated by optionalize
// on: 2017-10-19 08:41:18.030277912 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalUInt64Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value UInt64)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (UInt64, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def UInt64) UInt64

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() UInt64) UInt64

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() UInt64

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalUInt64Slice) OptionalUInt64Slice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb OptionalUInt64Slice) OptionalUInt64Slice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() OptionalUInt64Slice) OptionalUInt64Slice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value UInt64)) someOptionalUInt64SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalUInt64SliceHandler interface {
	None(fn func())
}

type _OptionalUInt64Slice struct {
	hasValue    bool
	unsafeValue UInt64
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalUInt64Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewOptionalUInt64Slice() OptionalUInt64Slice {
	opt := &_OptionalUInt64Slice{}
	opt.Take()
	return opt
}

func OptionalUInt64SliceFrom(value UInt64, hasValue bool) OptionalUInt64Slice {
	opt := &_OptionalUInt64Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_OptionalUInt64Slice) Take() {
	var value UInt64
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalUInt64Slice) From(value UInt64) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalUInt64Slice) Unwrap() (UInt64, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalUInt64Slice) UnwrapOr(def UInt64) UInt64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalUInt64Slice) UnwrapOrElse(fn func() UInt64) UInt64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalUInt64Slice) UnwrapOrPanic() UInt64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalUInt64Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalUInt64Slice) And(optb OptionalUInt64Slice) OptionalUInt64Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_OptionalUInt64Slice) Or(optb OptionalUInt64Slice) OptionalUInt64Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalUInt64Slice) OrElse(fn func() OptionalUInt64Slice) OptionalUInt64Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_OptionalUInt64Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_OptionalUInt64Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalUInt64Slice) Some(fn func(value UInt64)) someOptionalUInt64SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalUInt64SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalUInt64Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalUInt64SliceHandler struct {
	opt *_OptionalUInt64Slice
}

func (some _someOptionalUInt64SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalUInt64Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalUInt64Slice) getUnsafeValue() UInt64 {
	return opt.unsafeValue
}
