// Code generated by optionalize
// on: 2017-10-19 12:53:34.334904333 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type OptionalIntSlice struct {
	hasValue    bool
	unsafeValue Int
}

func NewOptionalIntSlice() OptionalIntSlice {
	opt := &OptionalIntSlice{}
	opt.Take()
	return *opt
}

func OptionalIntSliceFrom(value Int, hasValue bool) OptionalIntSlice {
	opt := &OptionalIntSlice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalIntSlice) Take() {
	var value Int
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalIntSlice) From(value Int) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalIntSlice) Unwrap() (Int, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalIntSlice) UnwrapOr(def Int) Int {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalIntSlice) UnwrapOrElse(fn func() Int) Int {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalIntSlice) UnwrapOrPanic() Int {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalIntSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalIntSlice) And(optb OptionalIntSlice) OptionalIntSlice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalIntSlice) Or(optb OptionalIntSlice) OptionalIntSlice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalIntSlice) OrElse(fn func() OptionalIntSlice) OptionalIntSlice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalIntSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalIntSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalIntSlice) Some(fn func(value Int)) someOptionalIntSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalIntSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalIntSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalIntSliceHandler struct {
	opt *OptionalIntSlice
}

func (some someOptionalIntSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalIntSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalIntSlice) getUnsafeValue() Int {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalIntSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalIntSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalIntSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
