// Code generated by optionalize
// on: 2017-10-19 08:58:27.510591411 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalUInt16Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value UInt16)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (UInt16, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def UInt16) UInt16

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() UInt16) UInt16

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() UInt16

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalUInt16Slice) OptionalUInt16Slice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb OptionalUInt16Slice) OptionalUInt16Slice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() OptionalUInt16Slice) OptionalUInt16Slice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value UInt16)) someOptionalUInt16SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalUInt16SliceHandler interface {
	None(fn func())
}

type _OptionalUInt16Slice struct {
	hasValue    bool
	unsafeValue UInt16
}

func NewOptionalUInt16Slice() OptionalUInt16Slice {
	opt := &_OptionalUInt16Slice{}
	opt.Take()
	return opt
}

func OptionalUInt16SliceFrom(value UInt16, hasValue bool) OptionalUInt16Slice {
	opt := &_OptionalUInt16Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_OptionalUInt16Slice) Take() {
	var value UInt16
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalUInt16Slice) From(value UInt16) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalUInt16Slice) Unwrap() (UInt16, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalUInt16Slice) UnwrapOr(def UInt16) UInt16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalUInt16Slice) UnwrapOrElse(fn func() UInt16) UInt16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalUInt16Slice) UnwrapOrPanic() UInt16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalUInt16Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalUInt16Slice) And(optb OptionalUInt16Slice) OptionalUInt16Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_OptionalUInt16Slice) Or(optb OptionalUInt16Slice) OptionalUInt16Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalUInt16Slice) OrElse(fn func() OptionalUInt16Slice) OptionalUInt16Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_OptionalUInt16Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_OptionalUInt16Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalUInt16Slice) Some(fn func(value UInt16)) someOptionalUInt16SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalUInt16SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalUInt16Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalUInt16SliceHandler struct {
	opt *_OptionalUInt16Slice
}

func (some _someOptionalUInt16SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalUInt16Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalUInt16Slice) getUnsafeValue() UInt16 {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalUInt16Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}
