// Code generated by optionalize
// on: 2017-10-19 12:56:06.046116871 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/Gurpartap/safer-go/optional/internal/convert"
	"github.com/pkg/errors"
)

type OptionalUIntSlice struct {
	hasValue    bool
	unsafeValue UInt
}

func NewOptionalUIntSlice() OptionalUIntSlice {
	opt := &OptionalUIntSlice{}
	opt.Take()
	return *opt
}

func OptionalUIntSliceFrom(value UInt, hasValue bool) OptionalUIntSlice {
	opt := &OptionalUIntSlice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalUIntSlice) Take() {
	var value UInt
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalUIntSlice) From(value UInt) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalUIntSlice) Unwrap() (UInt, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalUIntSlice) UnwrapOr(def UInt) UInt {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalUIntSlice) UnwrapOrElse(fn func() UInt) UInt {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalUIntSlice) UnwrapOrPanic() UInt {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalUIntSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalUIntSlice) And(optb OptionalUIntSlice) OptionalUIntSlice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalUIntSlice) Or(optb OptionalUIntSlice) OptionalUIntSlice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalUIntSlice) OrElse(fn func() OptionalUIntSlice) OptionalUIntSlice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalUIntSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalUIntSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalUIntSlice) Some(fn func(value UInt)) someOptionalUIntSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalUIntSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalUIntSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalUIntSliceHandler struct {
	opt *OptionalUIntSlice
}

func (some someOptionalUIntSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalUIntSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalUIntSlice) getUnsafeValue() UInt {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalUIntSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalUIntSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalUIntSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}

// Scan implements the sql Scanner interface.
func (opt *OptionalUIntSlice) Scan(value interface{}) error {
	if value == nil {
		opt.Take()
		return nil
	}

	var unsafeValue UInt
	err := convert.ConvertAssign(&unsafeValue, value)
	if err != nil {
		return err
	}
	opt.From(unsafeValue)

	return nil
}

// Value implements the driver Valuer interface.
func (opt OptionalUIntSlice) Value() (driver.Value, error) {
	if !opt.getHasValue() {
		return nil, nil
	}
	return opt.getUnsafeValue(), nil
}
