// Code generated by optionalize
// on: 2017-10-19 10:05:29.329467732 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type OptionalFloat64Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Float64)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Float64, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Float64) Float64

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Float64) Float64

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Float64

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalFloat64Slice) OptionalFloat64Slice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb OptionalFloat64Slice) OptionalFloat64Slice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() OptionalFloat64Slice) OptionalFloat64Slice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Float64)) someOptionalFloat64SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalFloat64SliceHandler interface {
	None(fn func())
}

type _OptionalFloat64Slice struct {
	hasValue    bool
	unsafeValue Float64
}

func NewOptionalFloat64Slice() OptionalFloat64Slice {
	opt := &_OptionalFloat64Slice{}
	opt.Take()
	return opt
}

func OptionalFloat64SliceFrom(value Float64, hasValue bool) OptionalFloat64Slice {
	opt := &_OptionalFloat64Slice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_OptionalFloat64Slice) Take() {
	var value Float64
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalFloat64Slice) From(value Float64) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalFloat64Slice) Unwrap() (Float64, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalFloat64Slice) UnwrapOr(def Float64) Float64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalFloat64Slice) UnwrapOrElse(fn func() Float64) Float64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalFloat64Slice) UnwrapOrPanic() Float64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalFloat64Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalFloat64Slice) And(optb OptionalFloat64Slice) OptionalFloat64Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_OptionalFloat64Slice) Or(optb OptionalFloat64Slice) OptionalFloat64Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalFloat64Slice) OrElse(fn func() OptionalFloat64Slice) OptionalFloat64Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_OptionalFloat64Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_OptionalFloat64Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalFloat64Slice) Some(fn func(value Float64)) someOptionalFloat64SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalFloat64SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalFloat64Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalFloat64SliceHandler struct {
	opt *_OptionalFloat64Slice
}

func (some _someOptionalFloat64SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalFloat64Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalFloat64Slice) getUnsafeValue() Float64 {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalFloat64Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json.Marshaler interface.
func (opt _OptionalFloat64Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (opt *_OptionalFloat64Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return err
	}
	opt.hasValue = true

	return nil
}
