// Code generated by optionalize
// on: 2017-10-19 08:41:20.863607922 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalStringSlice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value String)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (String, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def String) String

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() String) String

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() String

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalStringSlice) OptionalStringSlice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb OptionalStringSlice) OptionalStringSlice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() OptionalStringSlice) OptionalStringSlice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value String)) someOptionalStringSliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalStringSliceHandler interface {
	None(fn func())
}

type _OptionalStringSlice struct {
	hasValue    bool
	unsafeValue String
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalStringSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewOptionalStringSlice() OptionalStringSlice {
	opt := &_OptionalStringSlice{}
	opt.Take()
	return opt
}

func OptionalStringSliceFrom(value String, hasValue bool) OptionalStringSlice {
	opt := &_OptionalStringSlice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_OptionalStringSlice) Take() {
	var value String
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalStringSlice) From(value String) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalStringSlice) Unwrap() (String, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalStringSlice) UnwrapOr(def String) String {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalStringSlice) UnwrapOrElse(fn func() String) String {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalStringSlice) UnwrapOrPanic() String {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalStringSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalStringSlice) And(optb OptionalStringSlice) OptionalStringSlice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_OptionalStringSlice) Or(optb OptionalStringSlice) OptionalStringSlice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalStringSlice) OrElse(fn func() OptionalStringSlice) OptionalStringSlice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_OptionalStringSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_OptionalStringSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalStringSlice) Some(fn func(value String)) someOptionalStringSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalStringSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalStringSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalStringSliceHandler struct {
	opt *_OptionalStringSlice
}

func (some _someOptionalStringSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalStringSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalStringSlice) getUnsafeValue() String {
	return opt.unsafeValue
}
