// Code generated by optionalize
// on: 2017-10-19 12:56:04.287157349 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/Gurpartap/safer-go/optional/internal/convert"
	"github.com/pkg/errors"
)

type OptionalFloat32Slice struct {
	hasValue    bool
	unsafeValue Float32
}

func NewOptionalFloat32Slice() OptionalFloat32Slice {
	opt := &OptionalFloat32Slice{}
	opt.Take()
	return *opt
}

func OptionalFloat32SliceFrom(value Float32, hasValue bool) OptionalFloat32Slice {
	opt := &OptionalFloat32Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalFloat32Slice) Take() {
	var value Float32
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalFloat32Slice) From(value Float32) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalFloat32Slice) Unwrap() (Float32, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalFloat32Slice) UnwrapOr(def Float32) Float32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalFloat32Slice) UnwrapOrElse(fn func() Float32) Float32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalFloat32Slice) UnwrapOrPanic() Float32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalFloat32Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalFloat32Slice) And(optb OptionalFloat32Slice) OptionalFloat32Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalFloat32Slice) Or(optb OptionalFloat32Slice) OptionalFloat32Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalFloat32Slice) OrElse(fn func() OptionalFloat32Slice) OptionalFloat32Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalFloat32Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalFloat32Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalFloat32Slice) Some(fn func(value Float32)) someOptionalFloat32SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalFloat32SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalFloat32Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalFloat32SliceHandler struct {
	opt *OptionalFloat32Slice
}

func (some someOptionalFloat32SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalFloat32Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalFloat32Slice) getUnsafeValue() Float32 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalFloat32Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalFloat32Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalFloat32Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}

// Scan implements the sql Scanner interface.
func (opt *OptionalFloat32Slice) Scan(value interface{}) error {
	if value == nil {
		opt.Take()
		return nil
	}

	var unsafeValue Float32
	err := convert.ConvertAssign(&unsafeValue, value)
	if err != nil {
		return err
	}
	opt.From(unsafeValue)

	return nil
}

// Value implements the driver Valuer interface.
func (opt OptionalFloat32Slice) Value() (driver.Value, error) {
	if !opt.getHasValue() {
		return nil, nil
	}
	return opt.getUnsafeValue(), nil
}
