// Code generated by optionalize
// on: 2017-10-19 12:53:31.641652978 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type OptionalInt8Slice struct {
	hasValue    bool
	unsafeValue Int8
}

func NewOptionalInt8Slice() OptionalInt8Slice {
	opt := &OptionalInt8Slice{}
	opt.Take()
	return *opt
}

func OptionalInt8SliceFrom(value Int8, hasValue bool) OptionalInt8Slice {
	opt := &OptionalInt8Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalInt8Slice) Take() {
	var value Int8
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalInt8Slice) From(value Int8) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalInt8Slice) Unwrap() (Int8, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalInt8Slice) UnwrapOr(def Int8) Int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalInt8Slice) UnwrapOrElse(fn func() Int8) Int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalInt8Slice) UnwrapOrPanic() Int8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalInt8Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalInt8Slice) And(optb OptionalInt8Slice) OptionalInt8Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalInt8Slice) Or(optb OptionalInt8Slice) OptionalInt8Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalInt8Slice) OrElse(fn func() OptionalInt8Slice) OptionalInt8Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalInt8Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalInt8Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalInt8Slice) Some(fn func(value Int8)) someOptionalInt8SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalInt8SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalInt8Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalInt8SliceHandler struct {
	opt *OptionalInt8Slice
}

func (some someOptionalInt8SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalInt8Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalInt8Slice) getUnsafeValue() Int8 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalInt8Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalInt8Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalInt8Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
