// Code generated by optionalize
// on: 2017-10-19 12:53:31.046671152 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type OptionalUInt32Slice struct {
	hasValue    bool
	unsafeValue UInt32
}

func NewOptionalUInt32Slice() OptionalUInt32Slice {
	opt := &OptionalUInt32Slice{}
	opt.Take()
	return *opt
}

func OptionalUInt32SliceFrom(value UInt32, hasValue bool) OptionalUInt32Slice {
	opt := &OptionalUInt32Slice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *OptionalUInt32Slice) Take() {
	var value UInt32
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *OptionalUInt32Slice) From(value UInt32) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *OptionalUInt32Slice) Unwrap() (UInt32, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *OptionalUInt32Slice) UnwrapOr(def UInt32) UInt32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *OptionalUInt32Slice) UnwrapOrElse(fn func() UInt32) UInt32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *OptionalUInt32Slice) UnwrapOrPanic() UInt32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalUInt32Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *OptionalUInt32Slice) And(optb OptionalUInt32Slice) OptionalUInt32Slice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *OptionalUInt32Slice) Or(optb OptionalUInt32Slice) OptionalUInt32Slice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *OptionalUInt32Slice) OrElse(fn func() OptionalUInt32Slice) OptionalUInt32Slice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *OptionalUInt32Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *OptionalUInt32Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *OptionalUInt32Slice) Some(fn func(value UInt32)) someOptionalUInt32SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someOptionalUInt32SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *OptionalUInt32Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someOptionalUInt32SliceHandler struct {
	opt *OptionalUInt32Slice
}

func (some someOptionalUInt32SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *OptionalUInt32Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *OptionalUInt32Slice) getUnsafeValue() UInt32 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *OptionalUInt32Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt OptionalUInt32Slice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *OptionalUInt32Slice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
