// Code generated by optionalize
// on: 2017-09-10 10:30:46.428792046 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalInt32Slice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Int32)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Int32, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Int32) Int32

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Int32) Int32

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Int32

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalInt32Slice) OptionalInt32Slice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb OptionalInt32Slice) OptionalInt32Slice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() OptionalInt32Slice) OptionalInt32Slice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Int32)) someOptionalInt32SliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalInt32SliceHandler interface {
	None(fn func())
}

type _OptionalInt32Slice struct {
	hasValue    bool
	unsafeValue Int32
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalInt32Slice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewOptionalInt32Slice() OptionalInt32Slice {
	opt := &_OptionalInt32Slice{}
	opt.Take()
	return opt
}

func OptionalInt32SliceFrom(value Int32) OptionalInt32Slice {
	opt := &_OptionalInt32Slice{}
	opt.From(value)
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_OptionalInt32Slice) Take() {
	var value Int32
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalInt32Slice) From(value Int32) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalInt32Slice) Unwrap() (Int32, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalInt32Slice) UnwrapOr(def Int32) Int32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalInt32Slice) UnwrapOrElse(fn func() Int32) Int32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalInt32Slice) UnwrapOrPanic() Int32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalInt32Slice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalInt32Slice) And(optb OptionalInt32Slice) OptionalInt32Slice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_OptionalInt32Slice) Or(optb OptionalInt32Slice) OptionalInt32Slice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalInt32Slice) OrElse(fn func() OptionalInt32Slice) OptionalInt32Slice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_OptionalInt32Slice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_OptionalInt32Slice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalInt32Slice) Some(fn func(value Int32)) someOptionalInt32SliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalInt32SliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalInt32Slice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalInt32SliceHandler struct {
	opt *_OptionalInt32Slice
}

func (some _someOptionalInt32SliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalInt32Slice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalInt32Slice) getUnsafeValue() Int32 {
	return opt.unsafeValue
}
