// Code generated by optionalize
// on: 2017-10-19 08:41:21.172615568 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type OptionalIntSlice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Int)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Int, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Int) Int

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Int) Int

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Int

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalIntSlice) OptionalIntSlice

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb OptionalIntSlice) OptionalIntSlice

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() OptionalIntSlice) OptionalIntSlice

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Int)) someOptionalIntSliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalIntSliceHandler interface {
	None(fn func())
}

type _OptionalIntSlice struct {
	hasValue    bool
	unsafeValue Int
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalIntSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewOptionalIntSlice() OptionalIntSlice {
	opt := &_OptionalIntSlice{}
	opt.Take()
	return opt
}

func OptionalIntSliceFrom(value Int, hasValue bool) OptionalIntSlice {
	opt := &_OptionalIntSlice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_OptionalIntSlice) Take() {
	var value Int
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalIntSlice) From(value Int) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalIntSlice) Unwrap() (Int, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalIntSlice) UnwrapOr(def Int) Int {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalIntSlice) UnwrapOrElse(fn func() Int) Int {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalIntSlice) UnwrapOrPanic() Int {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalIntSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalIntSlice) And(optb OptionalIntSlice) OptionalIntSlice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_OptionalIntSlice) Or(optb OptionalIntSlice) OptionalIntSlice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalIntSlice) OrElse(fn func() OptionalIntSlice) OptionalIntSlice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_OptionalIntSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_OptionalIntSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalIntSlice) Some(fn func(value Int)) someOptionalIntSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalIntSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalIntSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalIntSliceHandler struct {
	opt *_OptionalIntSlice
}

func (some _someOptionalIntSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalIntSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalIntSlice) getUnsafeValue() Int {
	return opt.unsafeValue
}
