// Code generated by optionalize
// on: 2017-10-19 10:05:31.493389043 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type OptionalRuneSlice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value Rune)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (Rune, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def Rune) Rune

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() Rune) Rune

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() Rune

	// And returns None if the optional is None, otherwise returns optb.
	And(optb OptionalRuneSlice) OptionalRuneSlice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb OptionalRuneSlice) OptionalRuneSlice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() OptionalRuneSlice) OptionalRuneSlice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value Rune)) someOptionalRuneSliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someOptionalRuneSliceHandler interface {
	None(fn func())
}

type _OptionalRuneSlice struct {
	hasValue    bool
	unsafeValue Rune
}

func NewOptionalRuneSlice() OptionalRuneSlice {
	opt := &_OptionalRuneSlice{}
	opt.Take()
	return opt
}

func OptionalRuneSliceFrom(value Rune, hasValue bool) OptionalRuneSlice {
	opt := &_OptionalRuneSlice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_OptionalRuneSlice) Take() {
	var value Rune
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_OptionalRuneSlice) From(value Rune) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_OptionalRuneSlice) Unwrap() (Rune, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_OptionalRuneSlice) UnwrapOr(def Rune) Rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_OptionalRuneSlice) UnwrapOrElse(fn func() Rune) Rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_OptionalRuneSlice) UnwrapOrPanic() Rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap OptionalRuneSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_OptionalRuneSlice) And(optb OptionalRuneSlice) OptionalRuneSlice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_OptionalRuneSlice) Or(optb OptionalRuneSlice) OptionalRuneSlice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_OptionalRuneSlice) OrElse(fn func() OptionalRuneSlice) OptionalRuneSlice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_OptionalRuneSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_OptionalRuneSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_OptionalRuneSlice) Some(fn func(value Rune)) someOptionalRuneSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someOptionalRuneSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_OptionalRuneSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someOptionalRuneSliceHandler struct {
	opt *_OptionalRuneSlice
}

func (some _someOptionalRuneSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_OptionalRuneSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_OptionalRuneSlice) getUnsafeValue() Rune {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_OptionalRuneSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json.Marshaler interface.
func (opt _OptionalRuneSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (opt *_OptionalRuneSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return err
	}
	opt.hasValue = true

	return nil
}
