// Code generated by optionalize
// on: 2017-10-19 12:56:00.628299483 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/Gurpartap/safer-go/optional/internal/convert"
	"github.com/pkg/errors"
)

type RuneSlice struct {
	hasValue    bool
	unsafeValue []rune
}

func NewRuneSlice() RuneSlice {
	opt := &RuneSlice{}
	opt.Take()
	return *opt
}

func RuneSliceFrom(value []rune, hasValue bool) RuneSlice {
	opt := &RuneSlice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *RuneSlice) Take() {
	var value []rune
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *RuneSlice) From(value []rune) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *RuneSlice) Unwrap() ([]rune, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *RuneSlice) UnwrapOr(def []rune) []rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *RuneSlice) UnwrapOrElse(fn func() []rune) []rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *RuneSlice) UnwrapOrPanic() []rune {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap RuneSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *RuneSlice) And(optb RuneSlice) RuneSlice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *RuneSlice) Or(optb RuneSlice) RuneSlice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *RuneSlice) OrElse(fn func() RuneSlice) RuneSlice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *RuneSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *RuneSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *RuneSlice) Some(fn func(value []rune)) someRuneSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someRuneSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *RuneSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someRuneSliceHandler struct {
	opt *RuneSlice
}

func (some someRuneSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *RuneSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *RuneSlice) getUnsafeValue() []rune {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *RuneSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt RuneSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *RuneSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}

// Scan implements the sql Scanner interface.
func (opt *RuneSlice) Scan(value interface{}) error {
	if value == nil {
		opt.Take()
		return nil
	}

	var unsafeValue []rune
	err := convert.ConvertAssign(&unsafeValue, value)
	if err != nil {
		return err
	}
	opt.From(unsafeValue)

	return nil
}

// Value implements the driver Valuer interface.
func (opt RuneSlice) Value() (driver.Value, error) {
	if !opt.getHasValue() {
		return nil, nil
	}
	return opt.getUnsafeValue(), nil
}
