// Code generated by optionalize
// on: 2017-10-19 10:35:59.135285243 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type StringSlice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value []string)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() ([]string, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def []string) []string

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() []string) []string

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() []string

	// And returns None if the optional is None, otherwise returns optb.
	And(optb StringSlice) StringSlice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb StringSlice) StringSlice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() StringSlice) StringSlice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value []string)) someStringSliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someStringSliceHandler interface {
	None(fn func())
}

type _StringSlice struct {
	hasValue    bool
	unsafeValue []string
}

func NewStringSlice() StringSlice {
	opt := &_StringSlice{}
	opt.Take()
	return opt
}

func StringSliceFrom(value []string, hasValue bool) StringSlice {
	opt := &_StringSlice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_StringSlice) Take() {
	var value []string
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_StringSlice) From(value []string) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_StringSlice) Unwrap() ([]string, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_StringSlice) UnwrapOr(def []string) []string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_StringSlice) UnwrapOrElse(fn func() []string) []string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_StringSlice) UnwrapOrPanic() []string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap StringSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_StringSlice) And(optb StringSlice) StringSlice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_StringSlice) Or(optb StringSlice) StringSlice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_StringSlice) OrElse(fn func() StringSlice) StringSlice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_StringSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_StringSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_StringSlice) Some(fn func(value []string)) someStringSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someStringSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_StringSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someStringSliceHandler struct {
	opt *_StringSlice
}

func (some _someStringSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_StringSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_StringSlice) getUnsafeValue() []string {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *_StringSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt _StringSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *_StringSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
