// Code generated by optionalize
// on: 2017-10-19 10:35:52.603458505 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type String interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value string)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (string, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def string) string

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() string) string

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() string

	// And returns None if the optional is None, otherwise returns optb.
	And(optb String) String

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb String) String

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() String) String

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value string)) someStringHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someStringHandler interface {
	None(fn func())
}

type _String struct {
	hasValue    bool
	unsafeValue string
}

func NewString() String {
	opt := &_String{}
	opt.Take()
	return opt
}

func StringFrom(value string, hasValue bool) String {
	opt := &_String{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_String) Take() {
	var value string
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_String) From(value string) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_String) Unwrap() (string, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_String) UnwrapOr(def string) string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_String) UnwrapOrElse(fn func() string) string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_String) UnwrapOrPanic() string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap String")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_String) And(optb String) String {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_String) Or(optb String) String {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_String) OrElse(fn func() String) String {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_String) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_String) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_String) Some(fn func(value string)) someStringHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someStringHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_String) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someStringHandler struct {
	opt *_String
}

func (some _someStringHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_String) getHasValue() bool {
	return opt.hasValue
}

func (opt *_String) getUnsafeValue() string {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *_String) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt _String) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *_String) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
