// Code generated by optionalize
// on: 2017-10-19 12:53:28.01723568 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type StringSlice struct {
	hasValue    bool
	unsafeValue []string
}

func NewStringSlice() StringSlice {
	opt := &StringSlice{}
	opt.Take()
	return *opt
}

func StringSliceFrom(value []string, hasValue bool) StringSlice {
	opt := &StringSlice{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *StringSlice) Take() {
	var value []string
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *StringSlice) From(value []string) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *StringSlice) Unwrap() ([]string, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *StringSlice) UnwrapOr(def []string) []string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *StringSlice) UnwrapOrElse(fn func() []string) []string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *StringSlice) UnwrapOrPanic() []string {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap StringSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *StringSlice) And(optb StringSlice) StringSlice {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *StringSlice) Or(optb StringSlice) StringSlice {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *StringSlice) OrElse(fn func() StringSlice) StringSlice {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *StringSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *StringSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *StringSlice) Some(fn func(value []string)) someStringSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someStringSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *StringSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someStringSliceHandler struct {
	opt *StringSlice
}

func (some someStringSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *StringSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *StringSlice) getUnsafeValue() []string {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *StringSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt StringSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *StringSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
