// Code generated by optionalize
// on: 2017-10-19 10:05:25.823402814 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

type TimeSlice interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value []time.Time)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() ([]time.Time, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def []time.Time) []time.Time

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() []time.Time) []time.Time

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() []time.Time

	// And returns None if the optional is None, otherwise returns optb.
	And(optb TimeSlice) TimeSlice

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb TimeSlice) TimeSlice

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() TimeSlice) TimeSlice

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value []time.Time)) someTimeSliceHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someTimeSliceHandler interface {
	None(fn func())
}

type _TimeSlice struct {
	hasValue    bool
	unsafeValue []time.Time
}

func NewTimeSlice() TimeSlice {
	opt := &_TimeSlice{}
	opt.Take()
	return opt
}

func TimeSliceFrom(value []time.Time, hasValue bool) TimeSlice {
	opt := &_TimeSlice{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_TimeSlice) Take() {
	var value []time.Time
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_TimeSlice) From(value []time.Time) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_TimeSlice) Unwrap() ([]time.Time, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_TimeSlice) UnwrapOr(def []time.Time) []time.Time {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_TimeSlice) UnwrapOrElse(fn func() []time.Time) []time.Time {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_TimeSlice) UnwrapOrPanic() []time.Time {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap TimeSlice")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_TimeSlice) And(optb TimeSlice) TimeSlice {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_TimeSlice) Or(optb TimeSlice) TimeSlice {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_TimeSlice) OrElse(fn func() TimeSlice) TimeSlice {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_TimeSlice) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_TimeSlice) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_TimeSlice) Some(fn func(value []time.Time)) someTimeSliceHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someTimeSliceHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_TimeSlice) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someTimeSliceHandler struct {
	opt *_TimeSlice
}

func (some _someTimeSliceHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_TimeSlice) getHasValue() bool {
	return opt.hasValue
}

func (opt *_TimeSlice) getUnsafeValue() []time.Time {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_TimeSlice) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json.Marshaler interface.
func (opt _TimeSlice) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (opt *_TimeSlice) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return err
	}
	opt.hasValue = true

	return nil
}
