// Code generated by optionalize
// on: 2017-10-19 08:58:18.783356863 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type UInt interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value uint)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (uint, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def uint) uint

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() uint) uint

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() uint

	// And returns None if the optional is None, otherwise returns optb.
	And(optb UInt) UInt

	// Or returns the optional if it contains a value, otherwise returns optb.
	Or(optb UInt) UInt

	// OrElse returns the optional if it contains a value, otherwise calls fn
	// and returns the result.
	OrElse(fn func() UInt) UInt

	// IsSome returns true if the optional is a Some value.
	IsSome() bool

	// IsNone returns true if the optional is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value uint)) someUIntHandler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someUIntHandler interface {
	None(fn func())
}

type _UInt struct {
	hasValue    bool
	unsafeValue uint
}

func NewUInt() UInt {
	opt := &_UInt{}
	opt.Take()
	return opt
}

func UIntFrom(value uint, hasValue bool) UInt {
	opt := &_UInt{}
	if hasValue {
		opt.From(value)
	}
	return opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *_UInt) Take() {
	var value uint
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_UInt) From(value uint) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_UInt) Unwrap() (uint, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_UInt) UnwrapOr(def uint) uint {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_UInt) UnwrapOrElse(fn func() uint) uint {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_UInt) UnwrapOrPanic() uint {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap UInt")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_UInt) And(optb UInt) UInt {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *_UInt) Or(optb UInt) UInt {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_UInt) OrElse(fn func() UInt) UInt {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *_UInt) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *_UInt) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_UInt) Some(fn func(value uint)) someUIntHandler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someUIntHandler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_UInt) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someUIntHandler struct {
	opt *_UInt
}

func (some _someUIntHandler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_UInt) getHasValue() bool {
	return opt.hasValue
}

func (opt *_UInt) getUnsafeValue() uint {
	return opt.unsafeValue
}

// String conforms to fmt.Stringer interface.
func (opt *_UInt) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}
