// Code generated by optionalize
// on: 2017-10-19 12:53:17.01904319 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type UInt8 struct {
	hasValue    bool
	unsafeValue uint8
}

func NewUInt8() UInt8 {
	opt := &UInt8{}
	opt.Take()
	return *opt
}

func UInt8From(value uint8, hasValue bool) UInt8 {
	opt := &UInt8{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *UInt8) Take() {
	var value uint8
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *UInt8) From(value uint8) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *UInt8) Unwrap() (uint8, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *UInt8) UnwrapOr(def uint8) uint8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *UInt8) UnwrapOrElse(fn func() uint8) uint8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *UInt8) UnwrapOrPanic() uint8 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap UInt8")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *UInt8) And(optb UInt8) UInt8 {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *UInt8) Or(optb UInt8) UInt8 {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *UInt8) OrElse(fn func() UInt8) UInt8 {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *UInt8) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *UInt8) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *UInt8) Some(fn func(value uint8)) someUInt8Handler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someUInt8Handler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *UInt8) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someUInt8Handler struct {
	opt *UInt8
}

func (some someUInt8Handler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *UInt8) getHasValue() bool {
	return opt.hasValue
}

func (opt *UInt8) getUnsafeValue() uint8 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *UInt8) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt UInt8) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *UInt8) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
