// Code generated by optionalize
// on: 2017-10-19 12:55:50.49116642 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/Gurpartap/safer-go/optional/internal/convert"
	"github.com/pkg/errors"
)

type UInt32 struct {
	hasValue    bool
	unsafeValue uint32
}

func NewUInt32() UInt32 {
	opt := &UInt32{}
	opt.Take()
	return *opt
}

func UInt32From(value uint32, hasValue bool) UInt32 {
	opt := &UInt32{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *UInt32) Take() {
	var value uint32
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *UInt32) From(value uint32) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *UInt32) Unwrap() (uint32, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *UInt32) UnwrapOr(def uint32) uint32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *UInt32) UnwrapOrElse(fn func() uint32) uint32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *UInt32) UnwrapOrPanic() uint32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap UInt32")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *UInt32) And(optb UInt32) UInt32 {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *UInt32) Or(optb UInt32) UInt32 {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *UInt32) OrElse(fn func() UInt32) UInt32 {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *UInt32) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *UInt32) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *UInt32) Some(fn func(value uint32)) someUInt32Handler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someUInt32Handler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *UInt32) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someUInt32Handler struct {
	opt *UInt32
}

func (some someUInt32Handler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *UInt32) getHasValue() bool {
	return opt.hasValue
}

func (opt *UInt32) getUnsafeValue() uint32 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *UInt32) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt UInt32) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *UInt32) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}

// Scan implements the sql Scanner interface.
func (opt *UInt32) Scan(value interface{}) error {
	if value == nil {
		opt.Take()
		return nil
	}

	var unsafeValue uint32
	err := convert.ConvertAssign(&unsafeValue, value)
	if err != nil {
		return err
	}
	opt.From(unsafeValue)

	return nil
}

// Value implements the driver Valuer interface.
func (opt UInt32) Value() (driver.Value, error) {
	if !opt.getHasValue() {
		return nil, nil
	}
	return opt.getUnsafeValue(), nil
}
