// Code generated by optionalize
// on: 2017-09-10 10:30:32.980227845 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import "fmt"

type UInt32 interface {
	// Take takes the value out of the option, leaving a None in its place.
	Take()

	// From performs the conversion.
	From(value uint32)

	// Unwrap moves the value out of the optional, if it is Some(value).
	// This function returns multiple values, and if that's undesirable,
	// consider using Some and None functions.
	Unwrap() (uint32, bool)

	// UnwrapOr returns the contained value or a default.
	UnwrapOr(def uint32) uint32

	// UnwrapOrElse returns the contained value or computes it from a closure.
	UnwrapOrElse(fn func() uint32) uint32

	// UnwrapOrPanic returns the contained value or panics.
	UnwrapOrPanic() uint32

	// And returns None if the optional is None, otherwise returns optb.
	And(optb UInt32) UInt32

	// Or returns the option if it contains a value, otherwise returns optb.
	Or(optb UInt32) UInt32

	// OrElse returns the option if it contains a value, otherwise calls fn and
	// returns the result.
	OrElse(fn func() UInt32) UInt32

	// IsSome returns true if the option is a Some value.
	IsSome() bool

	// IsNone returns true if the option is a None value.
	IsNone() bool

	// Some executes the given closure if there is a Some value.
	Some(fn func(value uint32)) someUInt32Handler

	// None executes the given closure if there is a None value.
	None(fn func())
}

type someUInt32Handler interface {
	None(fn func())
}

type _UInt32 struct {
	hasValue    bool
	unsafeValue uint32
}

// String conforms to fmt.Stringer interface.
func (opt *_UInt32) String() string {
	if value, ok := opt.Unwrap(); ok {
		// some
		return fmt.Sprintf("Optional(%v)", value)
	}
	// none
	return "nil"
}

func NewUInt32() UInt32 {
	opt := &_UInt32{}
	opt.Take()
	return opt
}

func UInt32From(value uint32) UInt32 {
	opt := &_UInt32{}
	opt.From(value)
	return opt
}

// Take takes the value out of the option, leaving a None in its place.
func (opt *_UInt32) Take() {
	var value uint32
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *_UInt32) From(value uint32) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *_UInt32) Unwrap() (uint32, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *_UInt32) UnwrapOr(def uint32) uint32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *_UInt32) UnwrapOrElse(fn func() uint32) uint32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *_UInt32) UnwrapOrPanic() uint32 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap UInt32")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *_UInt32) And(optb UInt32) UInt32 {
	if !opt.getHasValue() {
		return opt
	}
	return optb
}

// Or returns the option if it contains a value, otherwise returns optb.
func (opt *_UInt32) Or(optb UInt32) UInt32 {
	if opt.getHasValue() {
		return opt
	}
	return optb
}

// OrElse returns the option if it contains a value, otherwise calls fn and
// returns the result.
func (opt *_UInt32) OrElse(fn func() UInt32) UInt32 {
	if opt.getHasValue() {
		return opt
	}
	return fn()
}

// IsSome returns true if the option is a Some value.
func (opt *_UInt32) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the option is a None value.
func (opt *_UInt32) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *_UInt32) Some(fn func(value uint32)) someUInt32Handler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return _someUInt32Handler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *_UInt32) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type _someUInt32Handler struct {
	opt *_UInt32
}

func (some _someUInt32Handler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *_UInt32) getHasValue() bool {
	return opt.hasValue
}

func (opt *_UInt32) getUnsafeValue() uint32 {
	return opt.unsafeValue
}
