// Code generated by optionalize
// on: 2017-10-19 12:53:17.347140677 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type UInt16 struct {
	hasValue    bool
	unsafeValue uint16
}

func NewUInt16() UInt16 {
	opt := &UInt16{}
	opt.Take()
	return *opt
}

func UInt16From(value uint16, hasValue bool) UInt16 {
	opt := &UInt16{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *UInt16) Take() {
	var value uint16
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *UInt16) From(value uint16) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *UInt16) Unwrap() (uint16, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *UInt16) UnwrapOr(def uint16) uint16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *UInt16) UnwrapOrElse(fn func() uint16) uint16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *UInt16) UnwrapOrPanic() uint16 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap UInt16")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *UInt16) And(optb UInt16) UInt16 {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *UInt16) Or(optb UInt16) UInt16 {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *UInt16) OrElse(fn func() UInt16) UInt16 {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *UInt16) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *UInt16) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *UInt16) Some(fn func(value uint16)) someUInt16Handler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someUInt16Handler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *UInt16) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someUInt16Handler struct {
	opt *UInt16
}

func (some someUInt16Handler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *UInt16) getHasValue() bool {
	return opt.hasValue
}

func (opt *UInt16) getUnsafeValue() uint16 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *UInt16) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt UInt16) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *UInt16) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
