// Code generated by optionalize
// on: 2017-10-19 12:53:17.971787306 &#43;0000 UTC
// from: github.com/Gurpartap/safer-go/optional/template/optional.go.tmpl

package optional

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

type UInt64 struct {
	hasValue    bool
	unsafeValue uint64
}

func NewUInt64() UInt64 {
	opt := &UInt64{}
	opt.Take()
	return *opt
}

func UInt64From(value uint64, hasValue bool) UInt64 {
	opt := &UInt64{}
	if hasValue {
		opt.From(value)
	}
	return *opt
}

// Take takes the value out of the optional, leaving a None in its place.
func (opt *UInt64) Take() {
	var value uint64
	opt.unsafeValue = value
	opt.hasValue = false
}

// From performs the conversion.
func (opt *UInt64) From(value uint64) {
	opt.unsafeValue = value
	opt.hasValue = true
}

// Unwrap moves the value out of the optional, if it is Some(value).
// This function returns multiple values, and if that's undesirable,
// consider using Some and None functions.
func (opt *UInt64) Unwrap() (uint64, bool) {
	return opt.getUnsafeValue(), opt.getHasValue()
}

// UnwrapOr returns the contained value or a default.
func (opt *UInt64) UnwrapOr(def uint64) uint64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return def
}

// UnwrapOrElse returns the contained value or computes it from a closure.
func (opt *UInt64) UnwrapOrElse(fn func() uint64) uint64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	return fn()
}

// UnwrapOrPanic returns the contained value or panics.
func (opt *UInt64) UnwrapOrPanic() uint64 {
	if opt.getHasValue() {
		return opt.getUnsafeValue()
	}
	panic("unable to unwrap UInt64")
}

// And returns None if the optional is None, otherwise returns optb.
func (opt *UInt64) And(optb UInt64) UInt64 {
	if !opt.getHasValue() {
		return *opt
	}
	return optb
}

// Or returns the optional if it contains a value, otherwise returns optb.
func (opt *UInt64) Or(optb UInt64) UInt64 {
	if opt.getHasValue() {
		return *opt
	}
	return optb
}

// OrElse returns the optional if it contains a value, otherwise calls fn and
// returns the result.
func (opt *UInt64) OrElse(fn func() UInt64) UInt64 {
	if opt.getHasValue() {
		return *opt
	}
	return fn()
}

// IsSome returns true if the optional is a Some value.
func (opt *UInt64) IsSome() bool {
	return opt.getHasValue()
}

// IsNone returns true if the optional is a None value.
func (opt *UInt64) IsNone() bool {
	return !opt.getHasValue()
}

// Some executes the given closure if there is a Some value.
func (opt *UInt64) Some(fn func(value uint64)) someUInt64Handler {
	if opt.getHasValue() {
		fn(opt.getUnsafeValue())
	}
	return someUInt64Handler{opt: opt}
}

// None executes the given closure if there is a None value.
func (opt *UInt64) None(fn func()) {
	if !opt.getHasValue() {
		fn()
	}
}

type someUInt64Handler struct {
	opt *UInt64
}

func (some someUInt64Handler) None(fn func()) {
	if !some.opt.getHasValue() {
		fn()
	}
}

func (opt *UInt64) getHasValue() bool {
	return opt.hasValue
}

func (opt *UInt64) getUnsafeValue() uint64 {
	return opt.unsafeValue
}

// String conforms to fmt Stringer interface.
func (opt *UInt64) String() string {
	if value, ok := opt.Unwrap(); ok {
		return fmt.Sprintf("Some(%v)", value)
	}
	return "None"
}

// MarshalJSON implements the json Marshaler interface.
func (opt UInt64) MarshalJSON() ([]byte, error) {
	if !opt.getHasValue() {
		return []byte("null"), nil
	}
	return json.Marshal(opt.getUnsafeValue())
}

// UnmarshalJSON implements the json Unmarshaler interface.
func (opt *UInt64) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) || data == nil {
		opt.Take()
		return nil
	}

	err := json.Unmarshal(data, &opt.unsafeValue)
	if err != nil {
		opt.hasValue = false
		return errors.WithStack(err)
	}
	opt.hasValue = true

	return nil
}
